(function(){

    var self = window.Console = {

        node: null,
        list: null,
        itemTemplate: null,

        prettyPrint: {

            output: function(className, o) {

                return ['<span class="'+ className +'">', o, '</span>'].join('');

            },

            /*
             * number(), string() and fn() methods are generated by
             * Console.init()
            */

           object: function(obj) {

              var name = (obj.toString()).match(/\[object (\w*)\]/)[1];
               
              return '<span class="object">' + name + '</span>';

           },

           fn: function(fn) {

                var data = fn.toString().match(/(\w*)(\([\w, ]*\))/),
                    fname = data[1] || 'function',
                    args = data[2];

                return this.output('function', fname + (' <code class="arguments">' + args + '</code>') );

           },

            check: function(something) {

                var pp = this,
                    output,
                    methods = [ pp.number, pp.string, pp.fn, pp.object ],
                    tests = [ 
                        (_.isNumber(Number(something)) && !_.isNaN(Number(something)) ),
                        _.isString(something),
                        (_.isFunction(something) && typeof something == 'function'),
                        (_.isObject(something) && typeof something != 'function'),
                    ];

                tests.forEach(function(value, index){

                    if ( value ) 
                        output = methods[index].call(pp, something);

                });

                return output || something;

            }            

        },


        insert: function(content) {

            var item = this.itemTemplate.cloneNode();

            if (content && content.nodeName) 
                item.appendChild(content);
            else
                item.innerHTML = content;

            $(this.list).prepend(item);

        },

        log: function(something) {

            if (_.isObject(something))
                this.dir(something);
            else
                this.insert(this.prettyPrint.check(something));

        },

        dir: function(object) {

            this.insert(new Widget.Inspector(object, undefined).node);

        },

        error: function(string) {

            this.log('Error: ' + string);

        },

        init: function(selector) {

            this.node = document.querySelector(selector);
            this.list = document.createElement('ul');

            this.itemTemplate = document.createElement('li');

            /* Generate prettyPrint helper functions */
            var pp = this.prettyPrint;
            pp.number = _.bind(pp.output, pp, 'number');
            pp.string = _.bind(pp.output, pp, 'string');
            //pp.fn = _.bind(pp.output, pp, 'function');

            this.node.appendChild(this.list);

        }
        
    };


})();
